name: '@lammu/amis-trpc' #包名
version: 1.0.0
description: trpc模板
author: lammu
license: MIT
private: false
type: module
main: ./src/index.ts
exports:
  .: ./src/index.ts
scripts:
  build:tsc: tsc
  build:ncc: ncc build ./src/index.ts -m -t -o build_ncc
  dev: tsx watch ./src/index.ts
  studio: pnpm prisma studio --port 7777
  formatSchema: pnpm prisma format
  migrate: pnpm prisma migrate dev
  generate: pnpm prisma generate
  watchSchema: pnpm prisma generate --watch
  pull: pnpm prisma db pull
  push: pnpm prisma db push
  watch: ts-node scripts/watchPrismaSchema.ts
dependencies:
  '@trpc/server': ^10.45.0
  '@prisma/client': ^5.2.0
  trpc-panel: ^1.3.4
  zod: ^3.22.4
devDependencies:
  zod-prisma: workspace:*
  '@types/node': ^20.10.0
  prisma: ^5.2.0
  prisma-dbml-generator: ^0.10.0
  tsx: ^4.7.0
  typescript: ^4.9.5
engines:
  node: '>18.0.0'
