name: lowcode-amis-main
version: 1.0.0
description: amis低代码项目
main: index.js
scripts: 
  # 设置monorepo.yaml中的配置
  set:config: local-cli set:config
keywords: []
author: lammu
license: MIT
dependencies:
  local-cli: workspace:*
engines:
  node: '>=18.3.0'
